language: python

sudo: false

python:
  - 3.6
  - 3.7
  - 3.8

cache: pip

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install coveralls
  - coveralls

deploy:
  provider: pypi
  on:
    tags: true
  username: "__token__"
  password:
    secure: cr5vOmqnfPdQ7VwlAvJiclaEI1+ohckw0YEPiIqOXdOvJjcAQbnIRztuTPnOh06QELUWKb7GhlHjIe5ghTnt+Ayu1jEyr52UDP9xiK6g0cdx6w7cvlMHwD3/CwP/+sWtFNaZK4ITObWNHC2+zieajoC+s7GSuHBwfOp8NvyPTOeDHcHc+71qu77FzsUfZY9POH2gms4vVhuXsgCBmR6rY6ev2OMylG0G5wo9myUcd4deQleUbzhf/MbkGYCobGL77AS6WGtU/lH8BCs2weYDWfHA37Fo/XJ43xGrapXySwLgO+/o+KON5tn081xqUQncMVzQ2NG2z0UHFtgYSCBMa07Fc/uELLfR6dHH0wB8p9G2lgvl48QH0MzjKv/fZqM/DWY580eOdlQqQ1Y+vGtc2gA4ApNBiXOiHLEjzWzNtXm772+h2OSujVyoJA+uKFW4xdvYKunDdLDrNa1ahkDI7tsN6A6CYkVTahSG1Zz8MaIhbVBm2AiaEe/IM0D3CRTOUc1s9Cn+Pl+13kwJPWm2twsZGJjTZaBsbPmlTMk5eG1Hj2VdcI6Odxh1kHW8ggAz2ccn/J6BXVYGYqN+sDrggLJyUZTLO4qDYXKTKBTngDUnqIIeIR3XZ+QjWANWVtpbLu0IBsFRfwD3YA9vHmxkgahnDvhyCt6rwBOuh2w8bSM=
